### ISSUE TITLE
Logged in user's session is not maintained

### ISSUE THREAD

**Issue by valentinoli** [serpentisx/road-watch#17]
This bug / issue is causing several other issues as well.

**Comment by valentinoli** [comment]
In progress?

**Comment by serpentisx** [comment]
This issue was hot-fixed with HttpSession in 490148e6f97ad505c50e84cd391474e0ab6260ab
A better, more dynamic and secure solution is in progress.

**Comment by valentinoli** [comment]
Excellent!
