### ISSUE TITLE
Organize CSS code and link to templates appropriately, avoiding any conflicts

### ISSUE THREAD

**Issue by valentinoli** [serpentisx/road-watch#31]
1. Move code for <header>, navigation and <footer> into separate CSS file(s).
2. Link relevant stylesheets to templates.
3. Add comments and explanations.

**Comment by serpentisx** [comment]
In progress. Mostly done.

**Comment by serpentisx** [comment]
Closed in 02c9bead693425a921d03cf5a4667dfea3e7ae07 b63d743ce43a6197deffec5f4e5e66aa45ad8ee5
