### ISSUE TITLE
Geolocation is not supported unless page is delivered by a secure connection

### ISSUE THREAD

**Issue by valentinoli** [serpentisx/road-watch#37]
The new post form uses the Geolocation API to enable the user to generate his or her location.
[See this post](https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only)

**Comment by valentinoli** [comment]
@serpentisx 
We have secured a secure connection now, so do you think we can close this one?

**Comment by serpentisx** [comment]
Closed in ad2c42b82e7543ff28a83845c33c1a44d386e1e1
