### ISSUE TITLE
New user's password is not saved in database so logging in as a new user does not work

### ISSUE THREAD

**Issue by valentinoli** [serpentisx/road-watch#56]

**Comment by bjarkivk** [comment]
Logging in in general just doesn't work, there is a problem with the password validation

**Comment by serpentisx** [comment]
Closed in 6d960d50bacc4820b1c7f206a3501aa31263de0a

**Comment by valentinoli** [comment]
Awesome. Thanks for fixing! My bad to have made the password variable transient - didn't realize the cause at the outset. I put it there for protection purposes but seems to have caused this issue.
