### ISSUE TITLE
Unknown error when sending e-mail

### ISSUE THREAD

**Issue by valentinoli** [serpentisx/road-watch#74]
app.exceptions.GenericExceptionHandler   : Exception: org.springframework.mail.MailAuthenticationException: Authentication failed; nested exception is javax.mail.AuthenticationFailedException: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbvg

**Comment by serpentisx** [comment]
Fixed
